### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by yotuke** [Liuwq-bit/LightGT#2]
尊敬的作者你好，我在学习你们的模型LightGT时，并没有找到实验所用的数据集，请问本实验的数据集是不开源的吗，需要自己制作？

**Comment by Liuwq-bit** [comment]
感谢你对本工作的关注与认可！

由于版权限制，我们无法直接放出实验中使用的数据集。

但是我们在README中给出了之前获取相应数据集的链接，你可以尝试申请数据集并自行处理。

也欢迎在其他数据集上进行实验，以验证本工作的效果。

**Comment by Liuwq-bit** [comment]
本模型所使用的数据集与[MMGCN](https://github.com/weiyinwei/MMGCN)相同，该仓库提供了简化版本的toy datasets。

可参考该数据集进行实验。

**Comment by yotuke** [comment]
好的，十分感谢您的回答，祝您多发顶刊
