### ISSUE TITLE
特征维度问题

### ISSUE THREAD

**Issue by TBI805** [Liuwq-bit/LightGT#3]
作者您好！非常感谢你们对社区的贡献！

我想请教一下 model.py 第113行， user_item 这个输入的有关问题。

1. 这里的 user_item 代表什么，它来自哪里？
2. 我用了MMGCN所提供的toy datasets运行LightGT后，发现user_item的size为[2048, 51], 这里的size是如何得来的，2048和51分别代表什么？

**Comment by Liuwq-bit** [comment]
感谢你对本工作的关注！

在训练数据中，部分用户拥有过多的正样本，出于对模型运行速度的考虑，我们对取出送入 transformer 的用户正样本个数设置了上限，该上限对应于超参 src_len。此处取出的每个用户的正样本，就是问题中的 user_item。

由于示例指令中设置 src_len 为50，因此每个用户最多取出50个正样本。

之后需要进一步取出这些正样本对应的各模态特征，而各模态特征的维度取决于所使用的预训练模型，问题2中提到的2048应该就是某一模态的特征维度。

在只使用物品模态特征的基础上，我们额外引入了一维作为对应 user 的特征，因此最终送入 transformer 的 seq_len 为 src_len+1，即问题2中提到的51。

但问题2令我感到困惑，送入模型 user_item 维度应为 [batch_size, 50]，[2048, 51] 可能为从某一模态取出对应的 item 特征并 transpose 后的结果，即：[modal_latent_dim, src_len+1]。但源代码中首先对各模态维度应用线性层降维为 latent_dim=64 再添加 user 特征并进行 transpose，因此应当只会出现 [64, 51]。

以下是对问题的总结：

1. user_item 为从训练数据中随机取出的每个用户的正样本。处理代码位于 dataloader.py。
2. 2048和51可能分别对应于某模态的特征维度和最终输入到 transformer 中的 seq_len。

**Comment by TBI805** [comment]
> 感谢你对本工作的关注！
> 
> 在训练数据中，部分用户拥有过多的正样本，出于对模型运行速度的考虑，我们对取出送入 transformer 的用户正样本个数设置了上限，该上限对应于超参 src_len。此处取出的每个用户的正样本，就是问题中的 user_item。
> 
> 由于示例指令中设置 src_len 为50，因此每个用户最多取出50个正样本。
> 
> 之后需要进一步取出这些正样本对应的各模态特征，而各模态特征的维度取决于所使用的预训练模型，问题2中提到的2048应该就是某一模态的特征维度。
> 
> 在只使用物品模态特征的基础上，我们额外引入了一维作为对应 user 的特征，因此最终送入 transformer 的 seq_len 为 src_len+1，即问题2中提到的51。
> 
> 但问题2令我感到困惑，送入模型 user_item 维度应为 [batch_size, 50]，[2048, 51] 可能为从某一模态取出对应的 item 特征并 transpose 后的结果，即：[modal_latent_dim, src_len+1]。但源代码中首先对各模态维度应用线性层降维为 latent_dim=64 再添加 user 特征并进行 transpose，因此应当只会出现 [64, 51]。
> 
> 以下是对问题的总结：
> 
> 1. user_item 为从训练数据中随机取出的每个用户的正样本。处理代码位于 dataloader.py。
> 2. 2048和51可能分别对应于某模态的特征维度和最终输入到 transformer 中的 seq_len。

感谢您的回复！

对于您在解答中所提到的困惑，我想用一张图简单说明一下。
![{21C71E53-E0D5-40b1-AA67-31DB49067FF0}](https://github.com/Liuwq-bit/LightGT/assets/34084035/fc845b2f-fea4-4c00-a84d-b0b418d8b7c6)

可以看到在断点处 user_item的size确实是[2048, 51]， 

这里的2048是特征维度还是batchsize的大小呢？

**Comment by Liuwq-bit** [comment]
不好意思，2048应为batch_size的大小。

送入模型的 user_item 的维度应为 [batch_size, 1+src_len]，第一维为预留放置 user 特征的位置，之后的 src_len 维为随机取出的 item。该操作也在 dataloader 中实现。

**Comment by TBI805** [comment]
再次感谢您的耐心解答！祝学习工作顺利！新年快乐！
