### ISSUE TITLE
关于数据格式的一些疑问

### ISSUE THREAD

**Issue by fanko79** [Liuwq-bit/LightGT#4]
您好，感谢您出色的工作，对于其中数据格式部分我有以下疑惑：
1.您在readme中对train.npy，val.npy和test.npy的描述为
-`train.npy`
   Train file. Each line is a user with her/his positive interactions with items: (userID and micro-video ID)  
-`val.npy`
   Validation file. Each line is a user several positive interactions with items: (userID and micro-video ID)  
-`test.npy`
   Test file. Each line is a user with several positive interactions with items: (userID and micro-video ID) 
我是否可以认为，train.npy，val.npy和test.npy的格式均为[userID, micro-video ID]，即每行数据由一对元组组成 (userID, micro-videoID)。其中，userID 表示用户的唯一标识符，micro-videoID 则代表用户与其有过正向交互的微视频的唯一标识符。
2.请问user_item_dict.npy文件的数据格式，您在readme中并未提到。

**Comment by Liuwq-bit** [comment]
train.npy的格式如您所述，每一行均为[userID, micro-video ID]：
![image](https://github.com/Liuwq-bit/LightGT/assets/60636530/a3642da2-648d-4422-9712-60a6c7017df2)
val.npy和test.npy的格式与您的理解有出入，为[userID, all interacted micro-video IDs]:
![image](https://github.com/Liuwq-bit/LightGT/assets/60636530/60428b89-85a8-4dd2-80c9-66b452882cd0)
user_item_dict.npy为保存各个user在训练集中对应micro-video IDs的字典，具体内容与train.npy一致：
![image](https://github.com/Liuwq-bit/LightGT/assets/60636530/6f6e5a48-f5c2-4992-a85a-5013868c1832)

**Comment by fanko79** [comment]
十分感谢你的回答，很好的解答了我的疑惑。
