### ISSUE TITLE
关于多头注意力和残差的训练耗时问题

### ISSUE THREAD

**Issue by Xuanqing-C** [Liuwq-bit/LightGT#6]
作者您好，对于论文中的一些现象我有点疑惑。在Table4和Table6中，当去掉多头自注意力和残差连接时，都显示训练耗时明显下降了，但是理论上多头自注意力和残差连接应该都没有增加计算复杂度或者引入额外的计算量。想请问下这个现象有什么比较合理的解释吗？

**Comment by Liuwq-bit** [comment]
我觉得这两个过程额外引入的计算量还是比较大的，目前想到的解释如下：
1）LightGT模型中，LightGCN的计算复杂度远小于Transformer Encoder部分，因此计算时间主要受Transformer部分影响；
2）对于论文中简化后的Transformer部分来说，主要操作就是自注意力的计算；
3）设置n头的自注意力需要额外进行（n-1）个QKV相关计算，相比单头操作直接增加（n-1）倍；
4）LightGT模型将多层简化后的Transformer进行堆叠，因此每层结构越复杂，总的计算量也会成倍提升；
5）添加其他组件后，反向传播过程同时需要进行更多计算，一定程度上拖累模型效率。
