### ISSUE TITLE
apply for preprocessing code

### ISSUE THREAD

**Issue by hongyurain** [Liuwq-bit/LightGT#7]
Hi,
  I am reading your paper published in SIGIR, I understand you have the copyright for Tiktok and Kwai, but for Movielens, it is published and we could download the interactions. Can you share the code how did you craw the trailers and preprocess this dataset then I could reproduce the results.

**Comment by Liuwq-bit** [comment]
Sorry for the late response.
The datasets of LightGT are directly provided by the first author. You may contract him to get the preprocessing code.
