### ISSUE TITLE
RuntimeError: addmm: Argument #3 (dense): Expected dim 0 size 1241, got 61471

### ISSUE THREAD

**Issue by dangan2162** [Liuwq-bit/LightGT#9]
When i run movielens 1M dataset with config in readme. It's raise error after load dataset and start training :
    all_emb = torch.sparse.mm(self.graph, all_emb)
RuntimeError: addmm: Argument #3 (dense): Expected dim 0 size 1241, got 61471
![Screenshot 2024-12-24 111425](https://github.com/user-attachments/assets/c467ecb6-b3ad-4b5d-822d-211ad4d609c9)

**Comment by Liuwq-bit** [comment]
It seems that the numbers of users and items does not match the dataset.
You can try modifying the numbers in [dataloader.py#L13-L14](https://github.com/Liuwq-bit/LightGT/blob/master/dataloader.py#L13-L14).

**Comment by dangan2162** [comment]
Thank you very much, it is the error of the npy file in the dataset
